import { useEffect, useState } from 'react'
import { supabase } from './lib/supabase'

function App() {
  const [name, setName] = useState('')
  const [content, setContent] = useState('')
  const [items, setItems] = useState([])
  const [status, setStatus] = useState('연결 확인 중...')
  const [loading, setLoading] = useState(false)

  const loadMessages = async () => {
    const { data, error } = await supabase
      .from('messages')
      .select('*')
      .order('created_at', { ascending: false })
      .limit(10)

    if (error) {
      setStatus(`불러오기 실패: ${error.message}`)
      return
    }

    setItems(data ?? [])
    setStatus(`연결 성공: ${data?.length ?? 0}개 메시지`)
  }

  useEffect(() => {
    loadMessages()
  }, [])

  const handleSubmit = async (event) => {
    event.preventDefault()

    if (!name.trim() || !content.trim()) {
      setStatus('이름과 메시지를 입력해 주세요.')
      return
    }

    setLoading(true)

    const { error } = await supabase.from('messages').insert([
      {
        name: name.trim(),
        content: content.trim(),
      },
    ])

    if (error) {
      setStatus(`저장 실패: ${error.message}`)
      setLoading(false)
      return
    }

    setName('')
    setContent('')
    await loadMessages()
    setStatus('저장 완료')
    setLoading(false)
  }

  return (
    <main style={{ fontFamily: 'sans-serif', padding: '2rem', lineHeight: 1.6, maxWidth: '760px', margin: '0 auto' }}>
      <h1>React + Supabase 데이터 입력</h1>
      <p>{status}</p>

      <form onSubmit={handleSubmit} style={{ display: 'grid', gap: '0.75rem', marginTop: '1rem' }}>
        <input
          value={name}
          onChange={(event) => setName(event.target.value)}
          placeholder="이름"
          style={{ padding: '0.75rem', borderRadius: '8px', border: '1px solid #cbd5e1' }}
        />
        <textarea
          value={content}
          onChange={(event) => setContent(event.target.value)}
          placeholder="메시지를 입력하세요"
          rows={4}
          style={{ padding: '0.75rem', borderRadius: '8px', border: '1px solid #cbd5e1' }}
        />
        <button type="submit" disabled={loading} style={{ padding: '0.75rem', borderRadius: '8px', border: 'none', background: '#2563eb', color: 'white', cursor: 'pointer' }}>
          {loading ? '저장 중...' : '저장하기'}
        </button>
      </form>

      <section style={{ marginTop: '1.5rem' }}>
        <h2>최근 메시지</h2>
        {items.length === 0 ? (
          <p>아직 저장된 데이터가 없습니다.</p>
        ) : (
          <ul style={{ paddingLeft: '1.2rem' }}>
            {items.map((item) => (
              <li key={item.id} style={{ marginBottom: '0.75rem' }}>
                <strong>{item.name}</strong>: {item.content}
              </li>
            ))}
          </ul>
        )}
      </section>

      <section style={{ marginTop: '1.5rem', background: '#f8fafc', padding: '1rem', borderRadius: '12px' }}>
        <h3>Supabase 테이블 준비</h3>
        <p>아직 테이블이 없다면 아래 SQL로 생성해 주세요.</p>
        <pre style={{ whiteSpace: 'pre-wrap', fontSize: '0.9rem' }}>{`create table if not exists public.messages (
  id bigint generated by default as identity primary key,
  name text not null,
  content text not null,
  created_at timestamp with time zone default now()
);`}</pre>
      </section>
    </main>
  )
}

export default App
